version: '3.8'

services:
  telegram-bot-manager:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - ./requirements.txt:/app/requirements.txt
    env_file:
      - .env.example
    ports:
      - "5000:5000"
    restart: always
    # Configurações específicas para dados móveis
    dns:
      - "8.8.8.8"
      - "1.1.1.1"
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge